---
title: "R Notebook"
author: paulbuckley
date: 23/12/2021
output: html_document
---


```{r}
library(data.table)
library(dplyr)
library(tidyr)
library(ggpubr)
library(Biostrings)
library(tidyverse)
library(foreach)
library(stringdist)
library(doParallel)

```
```{r}


WUHAN_PREDICTEDBINDING=readRDS("ORIGINAL_PEPTIDES_BINDING_SCORES_V2.rds")

WUHAN_PREDICTEDBINDING=WUHAN_PREDICTEDBINDING %>% select(! c(nM, Aff_Binder, Length, HydrophobicCount, HydroFraction))
WUHAN_PREDICTEDBINDING %>% head()
WUHAN_PREDICTEDBINDING %>% separate_rows_(cols=c("Predicted_Binding", "Thalf(h)", "EL-score", "EL_Rank","BA-score","BA_Rank","Ave","Binder","nM_41"), sep=",")%>% dplyr::filter(Binder=="BINDER")%>% arrange(Predicted_Binding) %>%
        readr::write_csv(file="/Users/paulbuckley/Nexus365/WIMM CCB - Koohy Group - Documents/Koohy Group/Effect_Mutation_Tcells/V11/SUBMITTED/R_R/Supplementary Tables/Table1_ImmunogenicCoV2Eps_predictedHLAbinders.csv")

```

## Useful functions

```{r}

# Function to provide a closest match. Used to match HLA Alleles across mixed output styles.
ClosestMatch2 = function(string, stringVector){

  stringVector[amatch(string, stringVector, maxDist=Inf)]

}

```

## Aims
- Create a DT 'AgretopicityDT' for downstream analysis that fr each paired WT-MT observation betrween Wuhan and BA1, contains all antigen presentation metrics.


# Read in Wuhan binding dataset

```{r}

WUHAN_PEPTIDES_BINDING_SCORES=readRDS("ORIGINAL_PEPTIDES_BINDING_SCORES_V2.rds")
WUHAN_PEPTIDES_BINDING_SCORES %>% head
WUHAN_PEPTIDES_BINDING_SCORES %>% nrow


```



# Read in Omicron mutants BA1 binding dataset

```{r}

OMICRON_PEPTIDES_BINDING_SCORES=readRDS("OMICRON_PEPTIDES_BINDING_SCORES_V2.rds")
OMICRON_PEPTIDES_BINDING_SCORES %>% head
OMICRON_PEPTIDES_BINDING_SCORES %>% nrow


```



# Read in mutations

```{r}
MUTATIONS = readRDS("OMICRON_EPITOPE_MUTATIONS.rds")
MUTATIONS %>% mutate(Length = nchar(Peptide))%>% filter(Protein == 'surface glycoprotein') %>% filter(Length== 9)%>% nrow

```


# join all

```{r}

MUTATIONS %>% inner_join(WUHAN_PEPTIDES_BINDING_SCORES)%>% nrow
MUTATIONS %>% inner_join(OMICRON_PEPTIDES_BINDING_SCORES) %>% nrow

FULL_MUTATIONS_DT=MUTATIONS %>% inner_join(WUHAN_PEPTIDES_BINDING_SCORES) %>% inner_join(OMICRON_PEPTIDES_BINDING_SCORES)

#saveRDS(FULL_MUTATIONS_DT,file="FULL_MUTATIONS_BINDING.rds")

```



# Agretopicity

```{r}
# create DT. One row per WT-MT, so separate collapsed rows.

AGRETOPICITY_DT=FULL_MUTATIONS_DT %>% select(Peptide, VariantAlignment, Protein, Predicted_Binding, nM_41, MT_nM_41,Binder,MT_Binder) %>%
        separate_rows_(cols = c("Predicted_Binding","nM_41","MT_nM_41","Binder","MT_Binder"),sep=",") %>%
        mutate(nM_41 = as.numeric(nM_41)) %>% mutate(MT_nM_41 = as.numeric(MT_nM_41))

```


```{r,dpi=300}

AGRETOPICITY_DT=AGRETOPICITY_DT %>% mutate(Agretopicity = MT_nM_41/nM_41)
saveRDS(AGRETOPICITY_DT, "AGRETOPICITY_DT.rds")
```
